### PR TITLE
Convert the app to Exponent, update to react-native 0.31

### PR DESCRIPTION
**Pull request by brentvatne**
You can try it here: https://getexponent.com/@notbrent/hacker-news

When you want to rebuild binaries you can do this: https://docs.getexponent.com/versions/v9.0.0/guides/building-standalone-apps.html

:smile: or don't merge if you don't want to, that's fine

### CODE REVIEW

**Comment by iSimar** [comment]
👍🏼 thanks

**Comment by brentvatne** [comment]
@iSimar - can you make me a collaborator on the repo? I want to make some more updates

**Comment by iSimar** [comment]
Hey brent, had to revert the PR - was having problems with exponent. Also I don't want exponent to be the only way to run the app, it can be one of the ways

**Comment by brentvatne** [comment]
Sure thing, no problem. What was the problem you were having?

**Pull request merged**
